[build]
  command   = "npm run build"
  publish   = "dist"

[build.environment]
  # Use a valid Node.js major version supported by Netlify
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
